function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

export namespace Flag {
  export const CODEPWN_AUTO_SHARE = truthy("CODEPWN_AUTO_SHARE")
  export const CODEPWN_GIT_BASH_PATH = process.env["CODEPWN_GIT_BASH_PATH"]
  export const CODEPWN_CONFIG = process.env["CODEPWN_CONFIG"]
  export declare const CODEPWN_CONFIG_DIR: string | undefined
  export const CODEPWN_CONFIG_CONTENT = process.env["CODEPWN_CONFIG_CONTENT"]
  export const CODEPWN_DISABLE_AUTOUPDATE = truthy("CODEPWN_DISABLE_AUTOUPDATE")
  export const CODEPWN_DISABLE_PRUNE = truthy("CODEPWN_DISABLE_PRUNE")
  export const CODEPWN_DISABLE_TERMINAL_TITLE = truthy("CODEPWN_DISABLE_TERMINAL_TITLE")
  export const CODEPWN_PERMISSION = process.env["CODEPWN_PERMISSION"]
  export const CODEPWN_DISABLE_DEFAULT_PLUGINS = truthy("CODEPWN_DISABLE_DEFAULT_PLUGINS")
  export const CODEPWN_DISABLE_LSP_DOWNLOAD = truthy("CODEPWN_DISABLE_LSP_DOWNLOAD")
  export const CODEPWN_ENABLE_EXPERIMENTAL_MODELS = truthy("CODEPWN_ENABLE_EXPERIMENTAL_MODELS")
  export const CODEPWN_DISABLE_AUTOCOMPACT = truthy("CODEPWN_DISABLE_AUTOCOMPACT")
  export const CODEPWN_DISABLE_MODELS_FETCH = truthy("CODEPWN_DISABLE_MODELS_FETCH")
  export const CODEPWN_DISABLE_CLAUDE_CODE = truthy("CODEPWN_DISABLE_CLAUDE_CODE")
  export const CODEPWN_DISABLE_CLAUDE_CODE_PROMPT =
    CODEPWN_DISABLE_CLAUDE_CODE || truthy("CODEPWN_DISABLE_CLAUDE_CODE_PROMPT")
  export const CODEPWN_DISABLE_CLAUDE_CODE_SKILLS =
    CODEPWN_DISABLE_CLAUDE_CODE || truthy("CODEPWN_DISABLE_CLAUDE_CODE_SKILLS")
  export declare const CODEPWN_DISABLE_PROJECT_CONFIG: boolean
  export const CODEPWN_FAKE_VCS = process.env["CODEPWN_FAKE_VCS"]
  export const CODEPWN_CLIENT = process.env["CODEPWN_CLIENT"] ?? "cli"
  export const CODEPWN_SERVER_PASSWORD = process.env["CODEPWN_SERVER_PASSWORD"]
  export const CODEPWN_SERVER_USERNAME = process.env["CODEPWN_SERVER_USERNAME"]

  // Experimental
  export const CODEPWN_EXPERIMENTAL = truthy("CODEPWN_EXPERIMENTAL")
  export const CODEPWN_EXPERIMENTAL_FILEWATCHER = truthy("CODEPWN_EXPERIMENTAL_FILEWATCHER")
  export const CODEPWN_EXPERIMENTAL_DISABLE_FILEWATCHER = truthy("CODEPWN_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const CODEPWN_EXPERIMENTAL_ICON_DISCOVERY =
    CODEPWN_EXPERIMENTAL || truthy("CODEPWN_EXPERIMENTAL_ICON_DISCOVERY")
  export const CODEPWN_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("CODEPWN_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const CODEPWN_ENABLE_EXA =
    truthy("CODEPWN_ENABLE_EXA") || CODEPWN_EXPERIMENTAL || truthy("CODEPWN_EXPERIMENTAL_EXA")
  export const CODEPWN_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("CODEPWN_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const CODEPWN_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("CODEPWN_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const CODEPWN_EXPERIMENTAL_OXFMT = CODEPWN_EXPERIMENTAL || truthy("CODEPWN_EXPERIMENTAL_OXFMT")
  export const CODEPWN_EXPERIMENTAL_LSP_TY = truthy("CODEPWN_EXPERIMENTAL_LSP_TY")
  export const CODEPWN_EXPERIMENTAL_LSP_TOOL = CODEPWN_EXPERIMENTAL || truthy("CODEPWN_EXPERIMENTAL_LSP_TOOL")
  export const CODEPWN_DISABLE_FILETIME_CHECK = truthy("CODEPWN_DISABLE_FILETIME_CHECK")
  export const CODEPWN_EXPERIMENTAL_PLAN_MODE = CODEPWN_EXPERIMENTAL || truthy("CODEPWN_EXPERIMENTAL_PLAN_MODE")
  export const CODEPWN_EXPERIMENTAL_MARKDOWN = truthy("CODEPWN_EXPERIMENTAL_MARKDOWN")
  export const CODEPWN_MODELS_URL = process.env["CODEPWN_MODELS_URL"]

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Backwards compatibility aliases
export const OPENCODE_AUTO_SHARE = Flag.CODEPWN_AUTO_SHARE
export const OPENCODE_GIT_BASH_PATH = Flag.CODEPWN_GIT_BASH_PATH
export const OPENCODE_CONFIG = Flag.CODEPWN_CONFIG
export const OPENCODE_CONFIG_DIR = Flag.CODEPWN_CONFIG_DIR
export const OPENCODE_CONFIG_CONTENT = Flag.CODEPWN_CONFIG_CONTENT
export const OPENCODE_DISABLE_AUTOUPDATE = Flag.CODEPWN_DISABLE_AUTOUPDATE
export const OPENCODE_DISABLE_PRUNE = Flag.CODEPWN_DISABLE_PRUNE
export const OPENCODE_DISABLE_TERMINAL_TITLE = Flag.CODEPWN_DISABLE_TERMINAL_TITLE
export const OPENCODE_PERMISSION = Flag.CODEPWN_PERMISSION
export const OPENCODE_DISABLE_DEFAULT_PLUGINS = Flag.CODEPWN_DISABLE_DEFAULT_PLUGINS
export const OPENCODE_DISABLE_LSP_DOWNLOAD = Flag.CODEPWN_DISABLE_LSP_DOWNLOAD
export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = Flag.CODEPWN_ENABLE_EXPERIMENTAL_MODELS
export const OPENCODE_DISABLE_AUTOCOMPACT = Flag.CODEPWN_DISABLE_AUTOCOMPACT
export const OPENCODE_DISABLE_MODELS_FETCH = Flag.CODEPWN_DISABLE_MODELS_FETCH
export const OPENCODE_DISABLE_CLAUDE_CODE = Flag.CODEPWN_DISABLE_CLAUDE_CODE
export const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT = Flag.CODEPWN_DISABLE_CLAUDE_CODE_PROMPT
export const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS = Flag.CODEPWN_DISABLE_CLAUDE_CODE_SKILLS
export const OPENCODE_FAKE_VCS = Flag.CODEPWN_FAKE_VCS
export const OPENCODE_CLIENT = Flag.CODEPWN_CLIENT
export const OPENCODE_SERVER_PASSWORD = Flag.CODEPWN_SERVER_PASSWORD
export const OPENCODE_SERVER_USERNAME = Flag.CODEPWN_SERVER_USERNAME
export const OPENCODE_EXPERIMENTAL = Flag.CODEPWN_EXPERIMENTAL
export const OPENCODE_EXPERIMENTAL_FILEWATCHER = Flag.CODEPWN_EXPERIMENTAL_FILEWATCHER
export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = Flag.CODEPWN_EXPERIMENTAL_DISABLE_FILEWATCHER
export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY = Flag.CODEPWN_EXPERIMENTAL_ICON_DISCOVERY
export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = Flag.CODEPWN_EXPERIMENTAL_DISABLE_COPY_ON_SELECT
export const OPENCODE_ENABLE_EXA = Flag.CODEPWN_ENABLE_EXA
export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = Flag.CODEPWN_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS
export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = Flag.CODEPWN_EXPERIMENTAL_OUTPUT_TOKEN_MAX
export const OPENCODE_EXPERIMENTAL_OXFMT = Flag.CODEPWN_EXPERIMENTAL_OXFMT
export const OPENCODE_EXPERIMENTAL_LSP_TY = Flag.CODEPWN_EXPERIMENTAL_LSP_TY
export const OPENCODE_EXPERIMENTAL_LSP_TOOL = Flag.CODEPWN_EXPERIMENTAL_LSP_TOOL
export const OPENCODE_DISABLE_FILETIME_CHECK = Flag.CODEPWN_DISABLE_FILETIME_CHECK
export const OPENCODE_EXPERIMENTAL_PLAN_MODE = Flag.CODEPWN_EXPERIMENTAL_PLAN_MODE
export const OPENCODE_EXPERIMENTAL_MARKDOWN = Flag.CODEPWN_EXPERIMENTAL_MARKDOWN
export const OPENCODE_MODELS_URL = Flag.CODEPWN_MODELS_URL

// Dynamic getter for CODEPWN_DISABLE_PROJECT_CONFIG
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "CODEPWN_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("CODEPWN_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for CODEPWN_CONFIG_DIR
// This must be evaluated at access time, not module load time,
// because external tooling may set this env var at runtime
Object.defineProperty(Flag, "CODEPWN_CONFIG_DIR", {
  get() {
    return process.env["CODEPWN_CONFIG_DIR"]
  },
  enumerable: true,
  configurable: false,
})

// Backwards compatibility
Object.defineProperty(Flag, "OPENCODE_DISABLE_PROJECT_CONFIG", {
  get() {
    return Flag.CODEPWN_DISABLE_PROJECT_CONFIG
  },
  enumerable: true,
  configurable: false,
})
